### ISSUE TITLE
Plugin is working I can't define a trigger action

### ISSUE THREAD

**Issue by ronzelver** [luisiam/homebridge-openpaths#2]
I've installed the plugin to enable geofencing for multiple person detection.
The plugin is working, I can see the status in my HomeKit app -> Occupancy Detected / Status Active
However, when I try to setup a trigger based on the occupancy status (anyone), I cannot select the device status, the configuration stops after selecting an 'Occupancy Sensor' in available services. Under available characteristics (e.g. sensor status) nothing is displayed?!
![img_0955](https://cloud.githubusercontent.com/assets/17887708/14723765/fff7a9d4-0812-11e6-91a2-63ecfba63a60.PNG)
![img_0956](https://cloud.githubusercontent.com/assets/17887708/14723766/fffbafde-0812-11e6-9298-2656462a1d83.PNG)

**Comment by luisiam** [comment]
Which app are you using? Are you using the Home app?

**Comment by ronzelver** [comment]
MyTouchHome

**Comment by luisiam** [comment]
Have you tried HMCatalog? I got it working on HMCatalog. I believe it works on Elgato Eve app, too. Problem is that existing HomeKit apps don't even support every single characteristic in HomeKit. I believe that it's more of an app issue since I got it working in other app.

This is from HMCatalog
![img_0266](https://cloud.githubusercontent.com/assets/16310467/14724101/0e94e2d0-07c9-11e6-8883-6ee84addaf20.PNG)

**Comment by ronzelver** [comment]
Elgato Eve is working, I can setup the trigger.
Is there a reason why all three Occupancy Detected sensors have no name attached to it in the selection dialog (same as in the 'At a Glance'-overview)? When I select the Occupancy Detected icon in the main screen, I see the names attached to it.

**Comment by luisiam** [comment]
It has to do with how the app is developed. Some developers just decide not to display the name of the service, assuming that there won't be more than 1 of the same service exist in the same device. I know some of the apps will show the name. HMCatalog is one of them

**Comment by ronzelver** [comment]
Thanks again!
